// Generated by CoffeeScript 1.6.3
import Ember from 'ember';
var SchoolItemController;

SchoolItemController = Ember.ObjectController.extend({
  newSchool: Ember.Object.create({
    name: '',
    type: '',
    city: '',
    state: '',
    adminuser: '',
    adminpassword: '',
    assisstantuser: '',
    assisstantpassword: ''
  }),
  typeaheadcontent: [
    Ember.Object.create({
      colour: "Red"
    }), Ember.Object.create({
      colour: "Green"
    }), Ember.Object.create({
      colour: "Blue"
    }), Ember.Object.create({
      colour: "Blue 1"
    }), Ember.Object.create({
      colour: "Blue 2"
    }), Ember.Object.create({
      colour: "Blue 3"
    }), Ember.Object.create({
      colour: "Blue 4"
    }), Ember.Object.create({
      colour: "Blue 5"
    }), Ember.Object.create({
      colour: "Blue 6"
    })
  ],
  schoolTypes: (function() {
    return this.store.find("school-type");
  }).property(),
  schoolStates: (function() {
    return this.store.find("state");
  }).property(),
  actions: {
    submit: function() {
      var school, schoolState, schoolType,
        _this = this;
      console.log("Sumbit!!");
      console.log(this.get('name'));
      console.log(this.newSchool.name);
      console.log(this.newSchool.type);
      console.log(this.newSchool.city);
      console.log(this.newSchool.state);
      schoolType = this.newSchool.type;
      schoolState = this.newSchool.state;
      school = this.store.createRecord('school', {
        name: this.newSchool.name,
        city: this.newSchool.city
      });
      school.save().then(function() {
        _this.store.find('school-type', schoolType).then(function(type) {
          return school.set('type', type);
        });
        return _this.store.find('state', schoolState).then(function(state) {
          return school.set('state', state);
        });
      });
      return this.transitionToRoute("schools");
    },
    cancel: function() {
      console.log("Cancel!!");
      return this.transitionToRoute("schools");
    }
  }
});

export default SchoolItemController;
