// Generated by CoffeeScript 1.6.3
import Ember from 'ember';
var EasyFormAdapter;

EasyFormAdapter = {
  name: 'easyForm',
  initialize: function() {
    Ember.EasyForm.Input.reopen({
      errorsChanged: function() {
        this.set('hasFocusedOut', true);
        return this.showValidationError();
      },
      classNameBindings: ['wrapperconfig.inputClass', 'wrapperErrorClass'],
      didInsertElement: function() {
        return this.addObserver('context.errors' + this.property + '.@each', this, 'errorsChanged');
      }
    });
    Ember.EasyForm.Error.reopen({
      errorText: (function() {
        return this.get('errors.firstObject.message');
      }).property('errors.firstObject.message', 'errors.firstObject').cacheable(),
      updateParentView: (function() {
        parentView.get('parentView');
        if (this.get('errors.length') > 0) {
          return parentView.set('wrapperErrorClass', 'has-error');
        } else {
          return parentView.set('wrapperErrorClass', false);
        }
      }).observes('errors.firstObject.message', 'errors.firstObject')
    });
    Ember.EasyForm.Submit.reopen({
      disabled: (function() {
        return this.get('formForModel.disableSubmit');
      }).property('formForModel.disableSubmit')
    });
    return Ember.EasyForm.Config.registerWrapper('default', {
      labelClass: 'control-label',
      inputClass: 'form-group',
      buttonClass: 'btn btn-primary',
      fieldErrorClass: 'has-error',
      errorClass: 'help-block'
    });
  }
};

export default EasyFormAdapter;
