// Generated by CoffeeScript 1.6.3
import Ember from 'ember';
var EasyFormAdapter;

EasyFormAdapter = {
  name: 'easyForm',
  initialize: function() {
    return Ember.EasyForm.Config.registerWrapper('default', {
      labelClass: 'control-label',
      inputClass: 'form-group',
      buttonClass: 'btn btn-primary',
      fieldErrorClass: 'has-error',
      errorClass: 'help-block'
    });
  }
};

export default EasyFormAdapter;
