// Generated by CoffeeScript 1.6.3
var ApiStubRoute;

ApiStubRoute = function(server) {
  return server.namespace('/api', function() {
    return server.get('/schools', function(req, res) {
      var schools;
      schools = [];
      return res.send(schools);
    });
  });
};

console.log("ApiStubRoute!!");

module.exports = ApiStubRoute;
