// Generated by CoffeeScript 1.6.3
import Ember from 'ember';
import Focusable from '../mixins/focusable';
import AsyncValidation from '../mixins/async-validation';
var SelectListComponent;

SelectListComponent = Ember.Component.extend(Focusable, AsyncValidation, {
  classNames: ['form-group'],
  content: "",
  prompt: "",
  required: false,
  validate: function(value, status) {
    if (this.get('required') && (!value || value.trim().length === 0)) {
      return status(false, this.get('label') + ' es requerido.');
    } else {
      return this._super(value, status);
    }
  }
});

export default SelectListComponent;
