// Generated by CoffeeScript 1.6.3
import Ember from 'ember';
var Focusable;

Focusable = Ember.Mixin.create({
  focused: false,
  focusIn: function(event) {
    return this.set('focused', true);
  },
  focusOut: function(event) {
    return this.set('focused', false);
  },
  autofocus: false,
  shouldAutoFocus: (function() {
    if (this.get('autofocus')) {
      return this.$('input').focus();
    }
  }).on('didInsertElement')
});

export default Focusable;
