// Generated by CoffeeScript 1.6.3
import Ember from 'ember';
var Router;

Router = Ember.Router.extend({
  location: PmENV.locationType
});

Router.map(function() {
  this.route('login');
  this.resource('schools', function() {
    return this.route('show', {
      path: ':school_id'
    });
  });
  this.resource('classrooms', {
    path: '/schools/:school_id/classrooms'
  });
  this.resource('classmates', {
    path: '/schools/:school_id/classrooms/:classroom_id'
  });
  this.route('setup');
  this.route('sociometricTestResults');
  this.route('studentDashboard', {
    path: '/student/:student_id'
  });
  this.route('sociometricTestAssigned');
  return this.route('surveyAssigned');
});

export default Router;
