// Generated by CoffeeScript 1.6.3
import Ember from 'ember';
var Router;

Router = Ember.Router.extend({
  location: PmENV.locationType
});

Router.map(function() {
  this.resource('schools', function() {
    return this.route('show', {
      path: ':school_id'
    });
  });
  this.resource('classrooms', {
    path: '/schools/:school_id/classrooms'
  });
  this.route('component-test');
  return this.route('helper-test');
});

export default Router;
