// Generated by CoffeeScript 1.6.3
import Ember from 'ember';
var Router;

Router = Ember.Router.extend({
  location: PmENV.locationType
});

Router.map(function() {
  this.route('login');
  this.resource('schools');
  this.resource('school', function() {
    this.route('new');
    this.route('edit', {
      path: '/school/edit/:school_id'
    });
    return this.route('delete', {
      path: '/school/delete/:school_id'
    });
  });
  this.resource('classrooms', {
    path: '/schools/:school_id/classrooms'
  });
  this.resource('classroom', function() {
    return this.route('new');
  });
  this.resource('classmates', {
    path: '/schools/:school_id/classrooms/:classroom_id'
  });
  this.route('setup');
  this.route('sociometricTestResults');
  this.route('surveyResults');
  this.route('sociogram');
  this.route('studentDashboard', {
    path: '/student/:student_id'
  });
  this.route('sociometricTestAssigned');
  this.route('surveyAssigned');
  return this.route('404', {
    path: '/*path'
  });
});

export default Router;
