// Generated by CoffeeScript 1.6.3
import Ember from 'ember';
var formatDateHelper;

formatDateHelper = Ember.Handlebars.makeBoundHelper(function(date) {
  return moment(date).format('DD-MMM-YYYY');
});

export default formatDateHelper;
