// Generated by CoffeeScript 1.6.3
import Ember from 'ember';
var formatDateHelper;

formatDateHelper = Ember.Handlebars.makeBoundHelper(function(date) {
  moment.lang('es');
  return moment(date).format('LL');
});

export default formatDateHelper;
