// Generated by CoffeeScript 1.6.3
import Ember from 'ember';
var schoolNewRoute;

schoolNewRoute = Ember.Route.extend({
  setupController: function(controller, model) {
    var newSchool;
    this._super(controller, model);
    controller.set('validationFields', []);
    newSchool = controller.get('newSchool');
    newSchool.set("name");
    newSchool.set("type");
    newSchool.set("city");
    return newSchool.set("state");
  }
});

export default schoolNewRoute;
