// Generated by CoffeeScript 1.6.3
import Ember from 'ember';
var classmatesRoute;

classmatesRoute = Ember.Route.extend({
  model: function(params) {
    return this.store.find('classroom', params.classroom_id).then(function(classmates) {
      return classmates;
    });
  }
});

export default classmatesRoute;
