// Generated by CoffeeScript 1.6.3
import Ember from 'ember';
var classroomsRoute;

classroomsRoute = Ember.Route.extend({
  model: function() {
    return this.store.modelFor('school').get('classrooms');
  }
});

export default classroomsRoute;
