// Generated by CoffeeScript 1.6.3
import Ember from 'ember';
var schoolRoute;

schoolRoute = Ember.Route.extend({
  model: function(params) {
    return this.store.find("school", params.school_id);
  }
});

export default schoolRoute;
