// Generated by CoffeeScript 1.6.3
import Ember from 'ember';
var schoolsRoute;

schoolsRoute = Ember.Route.extend({
  model: function() {
    return this.store.findAll("school");
  }
});

export default schoolsRoute;
