// Generated by CoffeeScript 1.6.3
import Ember from 'ember';
var schoolsRoute;

schoolsRoute = Ember.Route.extend({
  model: function() {
    return [
      {
        id: 1,
        name: 'School 1',
        type: 'PUBLIC'
      }, {
        id: 2,
        name: 'School 2',
        type: 'PRIVATE'
      }, {
        id: 3,
        name: 'School 3',
        type: 'PRIVATE'
      }
    ];
  }
});

export default schoolsRoute;
