// Generated by CoffeeScript 1.6.3
import Ember from 'ember';
var studentDashboardRoute;

studentDashboardRoute = Ember.Route.extend({
  model: function(params) {
    return this.store.find('student', params.student_id).then(function(student) {
      return student;
    });
  }
});

export default studentDashboardRoute;
