// Generated by CoffeeScript 1.6.3
import Ember from 'ember';
var schoolsController;

schoolsController = Ember.ArrayController.extend({
  itemController: "school",
  sortProperties: ['createdAt'],
  sortAscending: false,
  newSchool: Ember.Object.create({
    name: '',
    type: '',
    city: '',
    state: ''
  }),
  schoolTypes: (function() {
    return this.store.find("school-type");
  }).property(),
  schoolStates: (function() {
    return this.store.find("state");
  }).property(),
  modalButtons: [
    Ember.Object.create({
      title: 'Cancelar',
      clicked: "cancel",
      dismiss: 'modal'
    }), Ember.Object.create({
      title: 'Guardar',
      type: "primary",
      clicked: "submit",
      id: "btn_saveNewSchool"
    })
  ],
  actions: {
    addSchool: function() {
      console.log("Add School!!");
      return Bootstrap.ModalManager.show('schoolModal');
    },
    submit: function() {
      var school, schoolState, schoolType,
        _this = this;
      schoolType = this.newSchool.type;
      schoolState = this.newSchool.state;
      school = this.store.createRecord('school', {
        name: this.newSchool.name,
        city: this.newSchool.city
      });
      school.save().then(function() {
        _this.store.find('school-type', schoolType).then(function(type) {
          return school.set('type', type);
        });
        return _this.store.find('state', schoolState).then(function(state) {
          return school.set('state', state);
        });
      });
      this.set('newSchool.name', '');
      this.set('newSchool.type', '');
      this.set('newSchool.city', '');
      this.set('newSchool.state', '');
      return Bootstrap.ModalManager.hide('schoolModal', function(error) {
        school.rollback();
        return alert(error);
      });
    },
    cancel: function() {
      return console.log("Cancel!!");
    }
  }
});

export default schoolsController;
