// Generated by CoffeeScript 1.6.3
import Ember from 'ember';
var schoolsController;

schoolsController = Ember.ArrayController.extend({
  sortProperties: ['name'],
  sortAscending: false,
  schoolName: "",
  modalButtons: [
    Ember.Object.create({
      title: 'Cancelar',
      clicked: "cancel",
      dismiss: 'modal'
    }), Ember.Object.create({
      title: 'Guardar',
      type: "primary",
      clicked: "submit",
      id: "btn_saveNewSchool"
    })
  ],
  isValid: (function() {
    var isValid, msg, str;
    console.log("isValid()");
    msg = "";
    isValid = true;
    str = this.get('schoolName');
    console.log("schoolName = " + str);
    if (!str) {
      isValid = false;
      msg += "El campo no puede estar vacio.";
    }
    this.set('errName', msg);
    return isValid;
  }).property('schoolName'),
  actions: {
    classrooms: function() {
      return console.log("List Classrooms!!");
    },
    addSchool: function() {
      console.log("Add School!!");
      return Bootstrap.ModalManager.show('schoolModal');
    }
  }
});

export default schoolsController;
