// Generated by CoffeeScript 1.6.3
import Ember from 'ember';
var SchoolItemController;

SchoolItemController = Ember.ObjectController.extend({
  actions: {
    editSchool: function() {
      return console.log("Edit School!!");
    }
  }
});

export default SchoolItemController;
