// Generated by CoffeeScript 1.6.3
import Ember from 'ember';
var SchoolItemController;

SchoolItemController = Ember.ObjectController.extend({
  isNew: (function() {
    var isNew;
    console.log("isNew()");
    isNew = false;
    console.log(this.createdAt);
    console.log(moment(this.createdAt).startOf('day').fromNow());
    if (!(moment(this.createdAt).startOf('hour').fromNow() > 1)) {
      isNew = true;
    }
    return isNew;
  }).property('createdAt'),
  actions: {
    editSchool: function() {
      return console.log("Edit School!!");
    }
  }
});

export default SchoolItemController;
