// Generated by CoffeeScript 1.6.3
import Ember from 'ember';
var SchoolItemController;

SchoolItemController = Ember.ObjectController.extend({
  save: function() {
    return console.log("School saved!!");
  }
});

export default SchoolItemController;
