// Generated by CoffeeScript 1.6.3
import Ember from 'ember';
var schoolsController;

schoolsController = Ember.ArrayController.extend({
  sortProperties: ['createdAt'],
  sortAscending: false,
  isNew: (function() {
    var diff, isNew, target, today;
    isNew = false;
    today = moment();
    target = moment(this.createdAt);
    diff = today.diff(target, 'days');
    if (diff <= 1) {
      isNew = true;
    }
    return isNew;
  }).property('createdAt'),
  searchedContent: (function() {
    var regexp, stringToFilter;
    stringToFilter = this.get('school-filter');
    regexp = new RegExp(stringToFilter);
    return this.get('content').filter(function(item) {
      return regexp.test(item.get('name').toLowerCase());
    });
  }).property('school-filter', 'content.@each.name')
});

export default schoolsController;
