// Generated by CoffeeScript 1.6.3
import Ember from 'ember';
var EasyFormAdapter;

EasyFormAdapter = Ember.EasyForm.Config.registerWrapper('bootstrap', {
  formClass: '',
  fieldErrorClass: 'has-error',
  inputClass: 'form-group',
  errorClass: 'help-block error',
  hintClass: 'help-block',
  labelClass: ''
});

export default EasyFormAdapter;
