// Generated by CoffeeScript 1.6.3
import DS from 'ember-data';
var SchoolType;

SchoolType = DS.Model.extend({
  name: DS.attr('string')
});

SchoolType.reopenClass({
  FIXTURES: [
    {
      id: 'PUBLIC',
      name: 'Pública'
    }, {
      id: 'PRIVATE',
      name: 'Privada'
    }
  ]
});

export default SchoolType;
