// Generated by CoffeeScript 1.6.3
import DS from 'ember-data';
var UserRole;

UserRole = DS.Model.extend({
  name: DS.attr('string')
});

UserRole.reopenClass({
  FIXTURES: [
    {
      id: 'ADMIN',
      name: 'Administrador'
    }, {
      id: 'PRINCIPAL',
      name: 'Director'
    }, {
      id: 'ASSISTANT',
      name: 'Asistente'
    }, {
      id: 'STUDENT',
      name: 'Estudiante'
    }
  ]
});

export default UserRole;
