// Generated by CoffeeScript 1.6.3
import Ember from 'ember';
var schoolsView;

schoolsView = Ember.View.extend({
  templateName: 'schools',
  didInsertElement: function() {
    return $('#school-table').dataTable({
      "ordering": false,
      stateSave: true,
      "dom": '<"top"f>rt<"bottom"ip><"clear">',
      "columnDefs": [
        {
          "targets": [2],
          "visible": false,
          "searchable": false
        }, {
          "targets": [3],
          "searchable": false
        }
      ],
      "language": {
        "lengthMenu": "Mostrar _MENU_ registros por página",
        "zeroRecords": "No hay resultados.",
        "info": "Página _PAGE_ de _PAGES_",
        "infoEmpty": "No hay resultados.",
        "infoFiltered": "(de un total de _MAX_ registros)",
        "search": "Buscar",
        "paginate": {
          "first": "<<",
          "previous": "<",
          "next": ">",
          "last": ">>"
        }
      }
    });
  }
});

export default schoolsView;
